name: nt4f04unds_widgets
description: A new Flutter package project.
version: 1.0.3
homepage: https://github.com/nt4f04uNd/nt4f04unds_widgets
repository: https://github.com/nt4f04uNd/nt4f04unds_widgets
issue_tracker: https://github.com/nt4f04uNd/nt4f04unds_widgets/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  # Targeting flutter commit 183f0e797a3bf8aa1b35b650150f7522d5d10377

dependencies:
  async: ^2.4.2
  marquee: ^1.6.1
  equatable: ^1.2.5
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4
  multiple_localization:
    git:
      url: https://github.com/nt4f04uNd/flutter_multiple_localization
  flutter:
    sdk: flutter

dev_dependencies:
  intl_translation:
    git: 
      url: https://github.com/nt4f04uNd/intl_translation