name: nt4f04unds_widgets
description: A new Flutter package project.
version: 1.0.0-1
homepage: https://github.com/nt4f04uNd/nt4f04unds_widgets
repository: https://github.com/nt4f04uNd/nt4f04unds_widgets
issue_tracker: https://github.com/nt4f04uNd/nt4f04unds_widgets/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  marquee: ^1.6.1
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.12+4
  intl: '>=0.15.3 <0.17.0'
  flutter:
    sdk: flutter

dev_dependencies:
  intl_translation: ^0.17.10