name: Verify code and run tests

on:
  pull_request:
  push:
#    branches: TODO: Re-enable
#      - main
#      - master
#      - 'releases/**'

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check Dart formatting
        run: |
          echo "::add-matcher::${{ github.workspace }}/.github/problem-matchers/dart-format.json"
          dart format --output json --set-exit-if-changed .
          echo "::remove-matcher owner=dart-format"

      - name: Run Dart Linter
        run: |
          echo "::add-matcher::${{ github.workspace }}/.github/problem-matchers/flutter-analyze.json"
          flutter analyze --fatal-infos
          echo "::remove-matcher owner=flutter-analyze"

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
